### ISSUE TITLE
Unable to Lock/Unlock after a period of time. 

### ISSUE THREAD

**Issue by vincent861223** [ZacheryThomas/homeassistant-smartrent#15]
Thank you for developing such a nice integration. 

I was able to lock and unlock the door lock for the first few days after I setup this integration, however, it stopped working occasionally. I have the log related to this issue, which is related to "KeyError: 'access_token'". Any idea on how to fix this? Thank you!
```
2023-02-21 20:06:57 INFO (MainThread) [smartrent.utils] DoorLock        -> locked          -> false               
2023-02-21 20:06:57 INFO (MainThread) [smartrent.lock] Updating DoorLock
2023-02-21 20:06:59 INFO (MainThread) [smartrent.utils] Notifications   -> notifications   -> UNLOCK_VIA_RF       
2023-02-21 20:06:59 INFO (MainThread) [smartrent.lock] Updating DoorLock
2023-02-21 20:07:10 INFO (MainThread) [smartrent.utils] DoorLock        -> locked          -> true                
2023-02-21 20:07:10 INFO (MainThread) [smartrent.lock] Updating DoorLock
2023-02-21 20:07:11 INFO (MainThread) [smartrent.utils] Notifications   -> notifications   -> LOCK_VIA_RF         
2023-02-21 20:07:11 INFO (MainThread) [smartrent.lock] Updating DoorLock
2023-02-21 20:07:16 INFO (MainThread) [smartrent.utils] sending payload ["null", "null", "devices:3840830", "update_attributes", {"device_id": 3840830, "attributes": [{"name": "locked", "value": "false"}]}]
2023-02-21 20:07:16 INFO (MainThread) [smartrent.utils] Refreshing tokens with refresh token
2023-02-21 20:07:16 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [1702098208] 'access_token'
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/smartrent/utils.py", line 456, in _async_send_command
    await self._async_send_payload(device, payload)
  File "/usr/local/lib/python3.9/site-packages/smartrent/utils.py", line 483, in _async_send_payload
    async with websockets.connect(uri) as websocket:  # type: ignore
  File "/usr/local/lib/python3.9/site-packages/websockets/legacy/client.py", line 633, in __aenter__
    return await self
  File "/usr/local/lib/python3.9/site-packages/websockets/legacy/client.py", line 650, in __await_impl_timeout__
    return await asyncio.wait_for(self.__await_impl__(), self.open_timeout)
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 479, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.9/site-packages/websockets/legacy/client.py", line 658, in __await_impl__
    await protocol.handshake(
  File "/usr/local/lib/python3.9/site-packages/websockets/legacy/client.py", line 328, in handshake
    raise InvalidStatusCode(status_code, response_headers)
websockets.exceptions.InvalidStatusCode: server rejected WebSocket connection: HTTP 403

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 193, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1704, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1741, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 680, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 964, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 717, in _handle_entity_call
    await result
  File "/config/custom_components/smartrent/lock.py", line 67, in async_unlock
    await self.device.async_set_locked(False)
  File "/usr/local/lib/python3.9/site-packages/smartrent/lock.py", line 41, in async_set_locked
    await self._client._async_send_command(
  File "/usr/local/lib/python3.9/site-packages/smartrent/utils.py", line 465, in _async_send_command
    await self.async_refresh_token()
  File "/usr/local/lib/python3.9/site-packages/smartrent/utils.py", line 229, in async_refresh_token
    self._token = response["access_token"]
KeyError: 'access_token'
```

**Comment by vincent861223** [comment]
I found that this issue was actually related to my smartrent hub not connecting to the internet. Thank you again for such a great plugin.

**Comment by vincent861223** [comment]
Reopened the issue since this problem still happens occasionally.

**Comment by ZacheryThomas** [comment]
Looking into this! Not sure whats going on. Its been happening to me as well. Going to try debugging it soon.

**Comment by ZacheryThomas** [comment]
This issue should be fixed in the latest release. Feel free to let me know if it doesn't end up working out for you and I can take another look!

**Comment by vincent861223** [comment]
Thank you for fixing this issue so fast. I was able to control my door lock after I update it to the latest version, however, I found that I couldn't control my door lock after a few hours. I am not sure what happened. 
```
2023-02-26 14:32:03 INFO (MainThread) [smartrent.utils] sending payload ["null", "null", "devices:3840830", "update_attributes", {"device_id": 3840830, "attributes": [{"name": "locked", "value": "false"}]}]
2023-02-26 14:32:03 INFO (MainThread) [smartrent.utils] Refreshing tokens with refresh token
2023-02-26 14:32:03 INFO (MainThread) [smartrent.utils] Tokens refreshed!
2023-02-26 14:32:03 INFO (MainThread) [smartrent.utils] sending payload ["null", "null", "devices:3840830", "update_attributes", {"device_id": 3840830, "attributes": [{"name": "locked", "value": "false"}]}]
2023-02-26 14:32:04 INFO (MainThread) [smartrent.utils] Joining topic for Front Door - Lock:3840830 ...
```

**Comment by ZacheryThomas** [comment]
@vincent861223 No problem! Glad to see people using this thing I made.

Judging from the logs, it looks like the issues you are seeing may be a result of some connection issues between your hub and the internet. The plugin is at least sending stuff out to Smartrent (from the `sending payload` lines), but It looks like the hub never responds to the request.
