### ISSUE TITLE
Sensor NoneType object has no attribute keys

### ISSUE THREAD

**Issue by jerryc05** [ZacheryThomas/homeassistant-smartrent#6]
I encountered this error when setting up smartrent. 

```
2022-06-27 22:43:39 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up smartrent platform for sensor
Traceback (most recent call last):
  File "***/lib/python3.10/site-packages/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "***/.homeassistant/custom_components/smartrent/sensor.py", line 55, in async_setup_entry
    for device_class in device.keys():
AttributeError: 'NoneType' object has no attribute 'keys'
```

It did not however block the setup process of smartrent. It is just a error in console.

**Comment by jerryc05** [comment]
debugging shows that the `type(dev)` that causes error is a `<class 'smartrent.switch.BinarySwitch'>`, which is not included in `sensors_dict`

**Comment by ZacheryThomas** [comment]
Hi! Thanks for reachin out! Takin a look now

**Comment by jerryc05** [comment]
Seems like no more errors. Thanks!
